//! Verifies the audio-file decode paths end to end, including the WhatsApp
//! Opus-in-a-.jpg case and image rejection.
//! Run: cargo run --example decode_check -- <scratchpad_dir>

use std::io::Cursor;
use std::path::Path;

use unsound_lib::audiofile::decode_to_samples;

fn dur(samples: &[f32]) -> f32 {
    samples.len() as f32 / 16_000.0
}

/// Encode 16 kHz mono f32 samples to an Ogg-Opus byte stream, mirroring a
/// WhatsApp voice note.
fn encode_ogg_opus(samples_16k: &[f32]) -> Vec<u8> {
    use opus::{Application, Channels, Encoder};

    // Opus wants 48 kHz; upsample 16k → 48k by linear interpolation.
    let mut pcm48 = Vec::with_capacity(samples_16k.len() * 3);
    for w in samples_16k.windows(2) {
        pcm48.push(w[0]);
        pcm48.push(w[0] + (w[1] - w[0]) / 3.0);
        pcm48.push(w[0] + (w[1] - w[0]) * 2.0 / 3.0);
    }

    let mut enc = Encoder::new(48_000, Channels::Mono, Application::Voip).unwrap();
    let frame = 960; // 20 ms @ 48 kHz
    let mut writer = ogg::PacketWriter::new(Cursor::new(Vec::new()));
    let serial = 1u32;

    // OpusHead
    let mut head = vec![b'O', b'p', b'u', b's', b'H', b'e', b'a', b'd', 1, 1];
    head.extend_from_slice(&0u16.to_le_bytes()); // pre-skip
    head.extend_from_slice(&48_000u32.to_le_bytes()); // input rate
    head.extend_from_slice(&0u16.to_le_bytes()); // gain
    head.push(0); // channel mapping
    writer
        .write_packet(head, serial, ogg::PacketWriteEndInfo::EndPage, 0)
        .unwrap();

    // OpusTags
    let mut tags = b"OpusTags".to_vec();
    tags.extend_from_slice(&8u32.to_le_bytes());
    tags.extend_from_slice(b"unsound0");
    tags.extend_from_slice(&0u32.to_le_bytes());
    writer
        .write_packet(tags, serial, ogg::PacketWriteEndInfo::EndPage, 0)
        .unwrap();

    let mut granule = 0u64;
    let chunks: Vec<&[f32]> = pcm48.chunks(frame).collect();
    for (i, chunk) in chunks.iter().enumerate() {
        let mut input = chunk.to_vec();
        input.resize(frame, 0.0);
        let encoded = enc.encode_vec_float(&input, 4000).unwrap();
        granule += frame as u64;
        let end = if i == chunks.len() - 1 {
            ogg::PacketWriteEndInfo::EndStream
        } else {
            ogg::PacketWriteEndInfo::NormalPacket
        };
        writer.write_packet(encoded, serial, end, granule).unwrap();
    }
    writer.into_inner().into_inner()
}

fn check(label: &str, path: &Path) {
    match decode_to_samples(path) {
        Ok(s) => println!("  PASS  {label:22} {:.2}s, {} samples", dur(&s), s.len()),
        Err(e) => println!("  FAIL  {label:22} {e}"),
    }
}

fn check_rejects(label: &str, path: &Path, needle: &str) {
    match decode_to_samples(path) {
        Ok(_) => println!("  FAIL  {label:22} decoded but should have rejected"),
        Err(e) if e.contains(needle) => println!("  PASS  {label:22} rejected: {e}"),
        Err(e) => println!("  FAIL  {label:22} wrong error: {e}"),
    }
}

fn main() {
    let dir = std::env::args().nth(1).expect("pass the scratchpad dir");
    let dir = Path::new(&dir);

    // Optional second arg: check one arbitrary file and stop.
    if let Some(one) = std::env::args().nth(2) {
        check("file", Path::new(&one));
        return;
    }

    // Real audio files (generated by the shell script).
    for (label, name) in [
        ("wav 16k", "test_speech.wav"),
        ("m4a/aac", "test_speech.m4a"),
        ("caf", "test_speech.caf"),
        ("aiff", "test_speech.aiff"),
    ] {
        let p = dir.join(name);
        if p.exists() {
            check(label, &p);
        }
    }

    // Build an Ogg-Opus file from the wav, then a WhatsApp-style .jpg copy.
    let wav = dir.join("test_speech.wav");
    if wav.exists() {
        let samples = decode_to_samples(&wav).unwrap();
        let opus = encode_ogg_opus(&samples);
        let opus_path = dir.join("test_voice.opus");
        std::fs::write(&opus_path, &opus).unwrap();
        check("ogg-opus (.opus)", &opus_path);

        // The WhatsApp case: Opus bytes, wrong .jpg extension.
        let jpg_path = dir.join("whatsapp_voice.jpg");
        std::fs::write(&jpg_path, &opus).unwrap();
        check("opus as .jpg", &jpg_path);
    }

    // A genuine JPEG must be rejected with a helpful message.
    let real_jpg = dir.join("real_image.jpg");
    let mut jpg = vec![0xFF, 0xD8, 0xFF, 0xE0, 0, 16, b'J', b'F', b'I', b'F', 0];
    jpg.extend(std::iter::repeat(0u8).take(40));
    std::fs::write(&real_jpg, &jpg).unwrap();
    check_rejects("real jpeg", &real_jpg, "JPEG image");
}
